<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
*
*
*/

function hello_world_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.hello_world':
        $output= '';
        $output .= '<h3>' . t('About') . '</h3>';
        $output .= '<p>' . t('This is an example module.') . '</p>';
        return $output;
        
        default;
     }
}

function hello_world_cron() {

 drupal_set_message(t('DON’T PANIC, Its just CRON from Hello World!'), 'warning');

}